# Generated by Django 4.0.4 on 2022-04-28 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_filosofos_frase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAlimento', models.CharField(max_length=100)),
                ('Categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePlato', models.CharField(max_length=100)),
                ('Tiempo_Pre', models.IntegerField()),
                ('CategoriaP', models.CharField(max_length=100)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='quickstart.alimentos')),
            ],
        ),
        migrations.DeleteModel(
            name='Filosofos',
        ),
    ]
