# Generated by Django 4.0.4 on 2022-04-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_alimentosres_platosres_remove_platos_alimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAlimento', models.CharField(max_length=100)),
                ('Categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePlato', models.CharField(max_length=100)),
                ('Tiempo_Pre', models.IntegerField()),
                ('CategoriaP', models.CharField(max_length=100)),
                ('alimento', models.ManyToManyField(to='quickstart.alimento')),
            ],
        ),
        migrations.DeleteModel(
            name='AlimentosRes',
        ),
        migrations.DeleteModel(
            name='PlatosRes',
        ),
    ]
