# Generated by Django 4.0.4 on 2022-04-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_alimento_plato_delete_alimentosres_delete_platosres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
